local pd <const> = playdate
local gfx <const> = pd.graphics


quests = {
    {
        ["ID"] = 1,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Gather Berries",
        ["owner"] = "Junlop",
        ["introCopy"] = "Hello, I need to make a Berry Tart, but I am out of Berries, can you bring me 10 Berries?",
        ["inProgressCopy"] = "In case you forgot, I need 10 Berries to make a Berry Tart.",
        ["turninCopy"] = "Thank you, just one minute......  .. .. There! Have a Berry Tart for your troubles.",
        ["completeCopy"] = "Thank you!",
        ["description"] = "Junlop is looking to make a Berry Tart, but is out of berries. Help him gather 10 berries.",
        ["gatherItemID"] = 6,
        ["gatherItem"] = "Berries",
        ["quantity"] = 10,
        ["reward"] = "Berry Tart",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },
    {
        ["ID"] = 2,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "craft",
        ["title"] = "Berry Tarts for all!",
        ["owner"] = "Daryl",
        ["introCopy"] = "I'm looking for a good Berry Tart, you wouldnt happen to have one would you?",
        ["inProgressCopy"] = "I'm craving a Berry Tart.",
        ["turninCopy"] = "Thank you, heres some credits for your troubles. Now I can clear the road!",
        ["completeCopy"] = "Thank you!",
        ["description"] = "Daryl is looking for someone that can make a Berry Tart for him, are you up to the task?",
        ["gatherItem"] = "Berry Tart",
        ["quantity"] = 1,
        ["rewardCredits"] = 40,
        ["rewardReceived"] = false,
        ["recipeReceived"] = true,


    },
    {
        ["ID"] = 3,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Nanner Nanners",
        ["owner"] = "Eulo",
        ["introCopy"] =
        "I'm looking to make some Nanner Puddin, but I'm all out of Nanners. Can you go an fetch me some?",
        ["inProgressCopy"] = "I need 10 Nanners for my puddin.",
        ["turninCopy"] = "Thank you, let's get some down with puddin! Here's the recipe for your troubles.",
        ["completeCopy"] = "Puddin!",
        ["description"] =
        "Eulo is looking to make some Nanner Puddin, but is fresh out of Nanners. Bring back 10 Nanners to commence puddin time... whatever that is.",
        ["gatherItemID"] = 11,
        ["gatherItem"] = "Nanners",
        ["quantity"] = 10,
        ["reward"] = "Nanner Puddin",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },
    {
        ["ID"] = 4,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Meatball Special",
        ["owner"] = "Wuigi",
        ["introCopy"] =
        "I'm in need of some meatballs! Can you gather 5 meaty chunks for me?",
        ["inProgressCopy"] = "I need 5 meaty chunks for my Meatball Special.",
        ["turninCopy"] = "Thank you, let me whip up the special! Here's the recipe for your troubles.",
        ["completeCopy"] = "MMM..eatballs.",
        ["description"] =
        "Wuigi really wants a Meatball Special, help him by gathering 5 Meaty Chunks.",
        ["gatherItemID"] = 1,
        ["gatherItem"] = "Meaty Chunks",
        ["quantity"] = 5,
        ["reward"] = "Meatball Special",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },


    {
        ["ID"] = 5,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Pizza Party",
        ["owner"] = "Humphry",
        ["introCopy"] = "It's time for the annual Pizza Party, but I have no Tomas for my pizza! Can you bring me 15 Tomas?",
        ["inProgressCopy"] = "I need those Tomas Cosmo...",
        ["turninCopy"] = "Thank you, here's the recipe so you can make your own Cheesy Pizza!",
        ["completeCopy"] = "Thank you!",
        ["description"] = "Humphry needs 15 Tomas for his annual Pizza Party.",
        ["gatherItemID"] = 10,
        ["gatherItem"] = "Tomas",
        ["quantity"] = 15,
        ["reward"] = "Cheesy Pizza",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },

    {
        ["ID"] = 6,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "No soup for me",
        ["owner"] = "Jerry",
        ["introCopy"] = "I'm was looking forward to a nice Mushroom Soup today, but I'm out of Shroomas. Can you bring me 10 Shroomas?",
        ["inProgressCopy"] = "I really wanted soup...",
        ["turninCopy"] = "No soup for me? No soup for you! But here's the recipe so you can make your own Mushroom Soup!",
        ["completeCopy"] = "Thank you!",
        ["description"] = "Jerry needs 10 shroomas for his Mushroom Soup.",
        ["gatherItemID"] = 8,
        ["gatherItem"] = "Shrooma",
        ["quantity"] = 10,
        ["reward"] = "Mushroom Soup",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },

    {
        ["ID"] = 7,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "craft",
        ["title"] = "Mama Mia",
        ["owner"] = "Janice",
        ["introCopy"] = "I am craving some local delicacies and I heard that the Meatball Special was a delite. Bring me one pronto, delivery boy.",
        ["inProgressCopy"] = "That food better be warm when it gets here...",
        ["turninCopy"] = "Oh, this is delicious... thank you for the delivery, heres your tip.",
        ["completeCopy"] = "Mmmm... So good..",
        ["description"] = "Mama Mia, Janice seems to think you are her personal errand boy and requests the Meatball Special, well get to it!",
        ["gatherItem"] = "Meatball Special",
        ["quantity"] = 1,
        ["rewardCredits"] = 350,
        ["rewardReceived"] = false,
        ["recipeReceived"] = true,


    },

    {
        ["ID"] = 8,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Leaving Lima",
        ["owner"] = "Georwalt",
        ["introCopy"] = "You got an itch to get off this planet Cosmo? Well, I need you to take some Mushroom Soup to Laven. Once you have 4 bowls ready, deliver them to my friend Klimso.",
        ["inProgressCopy"] = "Don't forget, it's 4 bowls of Mushroom Soup!",
        ["turninCopy"] = "Thank you! This Mushroom Soup will be a hit on this planet! Heres one of our recipes, Toma Soup!",
        ["completeCopy"] = "Thanks!",
        ["description"] = "You're finally leaving this place! Off to Laven with 4 bowls of Mushroom Soup!",
        ["gatherItem"] = "Mushroom Soup",
        ["quantity"] = 4,
        ["reward"] = "Toma Soup",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,


    },
}
