local pd <const> = playdate
local gfx <const> = pd.graphics


quests = {
    -- LIMA QUESTS

    {
        ["ID"] = 1,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Gather Berries",
        ["owner"] = "Junlop",
        ["introCopy"] = "Hello, I need to make a Berry Tart, but I am out of Berries, can you bring me 10 Berries?",
        ["inProgressCopy"] = "In case you forgot, I need 10 Berries to make a Berry Tart.",
        ["turninCopy"] = "Thank you, just one minute......  .. .. There! Have a Berry Tart for your troubles.",
        ["completeCopy"] = "Thank you!",
        ["description"] = "Junlop is looking to make a Berry Tart, but is out of berries. Help him gather 10 berries.",
        ["gatherItemID"] = 6,
        ["gatherItem"] = "Berries",
        ["quantity"] = 10,
        ["reward"] = "Berry Tart",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },
    {
        ["ID"] = 2,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "craft",
        ["title"] = "Berry Tarts for all!",
        ["owner"] = "Daryl",
        ["introCopy"] = "I'm looking for a good Berry Tart, you wouldnt happen to have one would you?",
        ["inProgressCopy"] = "I'm craving a Berry Tart.",
        ["turninCopy"] = "Thank you, heres some credits for your troubles. Now I can clear the road!",
        ["completeCopy"] = "Thank you!",
        ["description"] = "Daryl is looking for someone that can make a Berry Tart for him, are you up to the task?",
        ["gatherItem"] = "Berry Tart",
        ["quantity"] = 1,
        ["rewardCredits"] = 40,
        ["rewardReceived"] = false,
        ["recipeReceived"] = true,


    },
    {
        ["ID"] = 3,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Nanner Nanners",
        ["owner"] = "Eulo",
        ["introCopy"] =
        "I'm looking to make some Nanner Puddin, but I'm all out of Nanners. Can you go an fetch me some?",
        ["inProgressCopy"] = "I need 10 Nanners for my puddin.",
        ["turninCopy"] = "Thank you, let's get some down with puddin! Here's the recipe for your troubles.",
        ["completeCopy"] = "Puddin!",
        ["description"] =
        "Eulo is looking to make some Nanner Puddin, but is fresh out of Nanners. Bring back 10 Nanners to commence puddin time... whatever that is.",
        ["gatherItemID"] = 11,
        ["gatherItem"] = "Nanners",
        ["quantity"] = 10,
        ["reward"] = "Nanner Puddin",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },
    {
        ["ID"] = 4,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Meatball Special",
        ["owner"] = "Wuigi",
        ["introCopy"] =
        "I'm in need of some meatballs! Can you gather 5 meaty chunks for me?",
        ["inProgressCopy"] = "I need 5 meaty chunks for my Meatball Special.",
        ["turninCopy"] = "Thank you, let me whip up the special! Here's the recipe for your troubles.",
        ["completeCopy"] = "MMM..eatballs.",
        ["description"] =
        "Wuigi really wants a Meatball Special, help him by gathering 5 Meaty Chunks.",
        ["gatherItemID"] = 1,
        ["gatherItem"] = "Meaty Chunks",
        ["quantity"] = 5,
        ["reward"] = "Meatball Special",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },


    {
        ["ID"] = 5,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Pizza Party",
        ["owner"] = "Humphry",
        ["introCopy"] = "It's time for the annual Pizza Party, but I have no Tomas for my pizza! Can you bring me 15 Tomas?",
        ["inProgressCopy"] = "I need those Tomas Cosmo...",
        ["turninCopy"] = "Thank you, here's the recipe so you can make your own Cheesy Pizza!",
        ["completeCopy"] = "Thank you!",
        ["description"] = "Humphry needs 15 Tomas for his annual Pizza Party.",
        ["gatherItemID"] = 10,
        ["gatherItem"] = "Tomas",
        ["quantity"] = 15,
        ["reward"] = "Cheesy Pizza",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },

    {
        ["ID"] = 6,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "No soup for me",
        ["owner"] = "Jerry",
        ["introCopy"] = "I'm was looking forward to a nice Mushroom Soup today, but I'm out of Shroomas. Can you bring me 10 Shroomas?",
        ["inProgressCopy"] = "I really wanted soup...",
        ["turninCopy"] = "No soup for me? No soup for you! But here's the recipe so you can make your own Mushroom Soup!",
        ["completeCopy"] = "Thank you!",
        ["description"] = "Jerry needs 10 shroomas for his Mushroom Soup.",
        ["gatherItemID"] = 8,
        ["gatherItem"] = "Shrooma",
        ["quantity"] = 10,
        ["reward"] = "Mushroom Soup",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },

    {
        ["ID"] = 7,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "craft",
        ["title"] = "Mama Mia",
        ["owner"] = "Janice",
        ["introCopy"] = "I am craving some local delicacies and I heard that the Meatball Special was a delite. Bring me one pronto, delivery boy.",
        ["inProgressCopy"] = "That food better be warm when it gets here...",
        ["turninCopy"] = "Oh, this is delicious... thank you for the delivery, heres your tip.",
        ["completeCopy"] = "Mmmm... So good..",
        ["description"] = "Mama Mia, Janice seems to think you are her personal errand boy and requests the Meatball Special, well get to it!",
        ["gatherItem"] = "Meatball Special",
        ["quantity"] = 1,
        ["rewardCredits"] = 350,
        ["rewardReceived"] = false,
        ["recipeReceived"] = true,


    },
    {
        ["ID"] = 8,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Laven Bound",
        ["owner"] = "Georwalt",
        ["introCopy"] = "I need to take some Mushroom Soup back home to Laven. Can you bring me 20 Shrooma?",
        ["inProgressCopy"] = "Don't forget, it's 20 Shrooma!",
        ["turninCopy"] = "Thank you! This Mushroom Soup will be a hit on Laven! Heres one of our recipes, Toma Soup!",
        ["completeCopy"] = "Thanks!",
        ["description"] = "Bring Georwalt 20 Shrooma so he can take it to his home planet!",
        ["gatherItemID"] = 8,
        ["gatherItem"] = "Shrooma",
        ["quantity"] = 10,
        ["reward"] = "Toma Soup",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },
    
    {
        ["ID"] = 9,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "craft",
        ["title"] = "Get the Shaft",
        ["owner"] = "Mulo",
        ["introCopy"] = "I hear you're off to Laven, but need some work done on your ship before it can fly. Bring me 3 bowls of Toma Soup and I'll get'r up and running",
        ["inProgressCopy"] = "Once I eat I can get started on your ship!",
        ["turninCopy"] = "Ah that should do it... now for my end of the deal, I've got your ship up and running, be sure to pull the crank out before you take off! Put it back in to exit the ship. Good ol' safety protocols.",
        ["completeCopy"] = "Thanks!",
        ["description"] = "Its time! Bring Mulo 3 bowls of Toma Soup and he will get your ship ready to take off!",
        ["gatherItem"] = "Toma Soup",
        ["quantity"] = 3,
        ["rewardCredits"] = 0,
        ["rewardReceived"] = false,
        ["recipeReceived"] = true,


    },

    -- LAVEN QUESTS
    {
        ["ID"] = 10,
        ["intro"] = false,
        ["found"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Welcome to Laven!",
        ["owner"] = "Big Chumski",
        ["introCopy"] = "Welcome to Laven! I'm looking for someone that can gather 15 Brussels for me. Watch out though, those Brusselflies are big!",
        ["inProgressCopy"] = "Don't forget, it's 15 Brussels!",
        ["turninCopy"] = "Thank you! This will help me with my Veggie Sando! Here's the recipe so you can make your own!",
        ["completeCopy"] = "Thanks!",
        ["description"] = "Bring Big Chumski 15 Brussels.",
        ["gatherItemID"] = 9,
        ["gatherItem"] = "Brussels",
        ["quantity"] = 15,
        ["reward"] = "Veggie Sando",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,

    },
    {
        ["ID"] = 11,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Easy Peasy Mac and Cheesy",
        ["owner"] = "Samson",
        ["introCopy"] = "I'm making some Mac n Cheese for a party, but I forgot to get Creama. Can you run to the store and get me 6 bottles of Crema?",
        ["inProgressCopy"] = "I can't beleive I forgot the 6 bottles of Creama",
        ["turninCopy"] = "Thank you! Here's the recipe for your collection!",
        ["completeCopy"] = "Thanks!",
        ["description"] = "Samson forgot the Crema for his Mac n Cheese! Bring him 6 bottles so he can finish his recipe.",
        ["gatherItemID"] = 29,
        ["gatherItem"] = "Crema",
        ["quantity"] = 6,
        ["reward"] = "Mac n Cheese",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,


    },
    {
        ["ID"] = 12,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "craft",
        ["title"] = "Pizza time",
        ["owner"] = "Gwenette",
        ["introCopy"] = "Hi! I'm in need of 5 Cheesy Pizzas for pizza night! The last delivery guy only gave me our Meaty Pizzas.",
        ["inProgressCopy"] = "Hurry with the 5 Cheesy Pizzas!",
        ["turninCopy"] = "Thank you! You're the hero of pizza night! Heres a tip for your troubles.",
        ["completeCopy"] = "Thanks!",
        ["description"] = "Its time! Bring Mulo 3 bowls of Toma Soup and he will get your ship ready to take off!",
        ["gatherItem"] = "Cheesy Pizza",
        ["quantity"] = 5,
        ["rewardCredits"] = 500,
        ["rewardReceived"] = false,
        ["recipeReceived"] = true,


    },

    {
        ["ID"] = 13,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "craft",
        ["title"] = "Sandos",
        ["owner"] = "Lammers",
        ["introCopy"] = "Hehe, I'm looking for a good Sando, can you bring me 2 Veggie Sandos?",
        ["inProgressCopy"] = "You got those Sandos yet?",
        ["turninCopy"] = "MMM... Mmm. Those were some tasty sandos, thanks! Here's your tip.",
        ["completeCopy"] = "Sandos!!",
        ["description"] = "Lammers is looking for some Sandos, bring him 2 Veggie Sandos pronto!",
        ["gatherItem"] = "Veggie Sando",
        ["quantity"] = 2,
        ["rewardCredits"] = 600,
        ["rewardReceived"] = false,
        ["recipeReceived"] = true,


    },

    {
        ["ID"] = 14,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Meat Lover",
        ["owner"] = "Lenneux",
        ["introCopy"] = "I have some cheesy pizzas, but I'd like to add more to it. Can you bring me 10 Meaty Chunks? I hear theyre specific to Lima.",
        ["inProgressCopy"] = "You won't find Meaty Chunks here, you'll have to get them on Lima.",
        ["turninCopy"] = "Thank you! Here's the recipe for a Meaty Pizza!",
        ["completeCopy"] = "Thanks!",
        ["description"] = "Lenneux wants to up their pizza game, bring them 10 Meaty Chunks from Lima.",
        ["gatherItemID"] = 1,
        ["gatherItem"] = "Meaty Chunks",
        ["quantity"] = 10,
        ["reward"] = "Meaty Pizza",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,


    },

    {
        ["ID"] = 15,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Cookie Caper",
        ["owner"] = "Cindell",
        ["introCopy"] = "Someone took all my cookies! Can you bring me a dozen Doughballs so I can make a new batch?",
        ["inProgressCopy"] = "I hope whoever stole those cookies is happy...",
        ["turninCopy"] = "Thank you! Here's my recipe to back your own Cookies!",
        ["completeCopy"] = "Thanks!",
        ["description"] = "Cindell is in need of more Doughballs to bake a new batch of cookies. Bring her 12 Doughballs.",
        ["gatherItemID"] = 26,
        ["gatherItem"] = "Doughball",
        ["quantity"] = 12,
        ["reward"] = "Cookies",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,


    },

    {
        ["ID"] = 16,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "gather",
        ["title"] = "Let's talk Chops",
        ["owner"] = "Wetzel",
        ["introCopy"] = "Hey there! I need some Big Chops to fry up for dinner, can you bring me 10 Big Chops?",
        ["inProgressCopy"] = "Cant wait to see what you bring back!",
        ["turninCopy"] = "Oh these are perfect, here's my recipe in case you want to make your own!",
        ["completeCopy"] = "Thanks!",
        ["description"] = "Wetzel is making Fried Chops for dinner, bring him 10 Big Chops.",
        ["gatherItemID"] = 3,
        ["gatherItem"] = "Big Chop",
        ["quantity"] = 10,
        ["reward"] = "Fried Chop",
        ["rewardQty"] = 1,
        ["rewardReceived"] = false,
        ["recipeReceived"] = false,


    },

    {
        ["ID"] = 17,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "craft",
        ["title"] = "Pizza Again",
        ["owner"] = "Tuilo",
        ["introCopy"] = "Hi, I'm looking for a good Meaty Pizza, could you make me one?",
        ["inProgressCopy"] = "I'm ready for pizza!",
        ["turninCopy"] = "Oh yeah, thats it. Meaty Pizza is the best! Here's your tip",
        ["completeCopy"] = "Thanks for the pizza!",
        ["description"] = "Tuilo is looking for a good Meaty Pizza, bring her one in 30 parsecs or less!",
        ["gatherItem"] = "Meaty Pizza",
        ["quantity"] = 1,
        ["rewardCredits"] = 400,
        ["rewardReceived"] = false,
        ["recipeReceived"] = true,


    },

    {
        ["ID"] = 18,
        ["found"] = false,
        ["intro"] = false,
        ["inProgress"] = false,
        ["complete"] = false,
        ["type"] = "craft",
        ["title"] = "Cookies for Mushroo",
        ["owner"] = "Janzlo",
        ["introCopy"] = "Hi, I'm off to Mushroo now that the barrier's being lifted, can you bring me 5 Cookies to take to my friends?",
        ["inProgressCopy"] = "Hurry! The barrier is almost gone!",
        ["turninCopy"] = "Thank you! Here's your tip for the speediness. ",
        ["completeCopy"] = "Be sure to check out Mushroo! Its south of Lima (or below... whatever whatever space terms...)",
        ["description"] = "Mushroo is almost ready to visit! Bring Janzlo 5 Cookies to take to her friends.",
        ["gatherItem"] = "Cookies",
        ["quantity"] = 5,
        ["rewardCredits"] = 800,
        ["rewardReceived"] = false,
        ["recipeReceived"] = true,


    },

}
